[project]
name = "metatensor-lj-test"
description = "Package for testing metatensor model integration"
dynamic = ["version"]
dependencies = [
    "torch >=1.12",
    "metatensor-torch >=0.5.0,<0.6.0"
]

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "setuptools-scm",
    "wheel",
    "torch >=1.12"
]


[tool.setuptools_scm]
